omou-frontend/src/components/FeatureViews/Registration/Form.js
omou-frontend/src/components/FeatureViews/Registration/FullRegistration.js
omou-frontend/src/components/FeatureViews/Registration/Validations.js
omou-frontend/src/reducers/initialState.js

Close #28
Validation should function properly for all fields now, buttons are disabled when their action is invalid, form input is preserved even if the page is reloaded, and select field functionality has been improved.

Improved form functionality and validation

---

omou-frontend/src/components/FeatureViews/Registration/FullRegistration.js
omou-frontend/src/components/FeatureViews/Registration/registration.scss

Buttons have been moved down and indentation for cards is removed.

Fixed position for #39

---

omou-frontend/src/components/FeatureViews/Registration/RegistrationActions.js

Close #48
Registering for a new course and tutor are now combined into one dropdown with an option for either choice.

Combine register course and tutor into one dropdown

---

omou-frontend/src/components/FeatureViews/Registration/RegistrationActions.js
omou-frontend/src/components/FeatureViews/Registration/registration.scss

Addressed @dhuangg 's requested changes

Combined button

---

omou-frontend/src/actions/actionTypes.js
omou-frontend/src/actions/registrationActions.js
omou-frontend/src/components/FeatureViews/Registration/CourseCategory.js
omou-frontend/src/components/FeatureViews/Registration/Form.js
omou-frontend/src/components/FeatureViews/Registration/registration.scss
omou-frontend/src/reducers/initialState.js
omou-frontend/src/reducers/registrationReducer.js

Added dropdown menu to student

---

omou-frontend/src/components/FeatureViews/Registration/Form.js
omou-frontend/src/components/FeatureViews/Registration/registration.scss
omou-frontend/src/reducers/registrationReducer.js

Delete button stopped working.

needs fixing

---

omou-frontend/src/components/FeatureViews/Accounts/Accounts.scss
omou-frontend/src/components/FeatureViews/Accounts/ComponentViewer.js
omou-frontend/src/components/FeatureViews/Accounts/ProfileHeading.js
omou-frontend/src/components/FeatureViews/Accounts/TabComponents/PayCourses.js
omou-frontend/src/components/FeatureViews/Accounts/TabComponents/StudentInfo.js
omou-frontend/src/components/FeatureViews/Accounts/TabComponents/TabComponents.scss
omou-frontend/src/components/FeatureViews/Accounts/UserProfile.js
omou-frontend/src/reducers/initialState.js
omou-frontend/src/theme/_colors.scss

basic view of parent profile
@NeilAllavarpu

created parent profile

---

omou-frontend/src/components/FeatureViews/Registration/CourseList.js
omou-frontend/src/components/FeatureViews/Registration/Registration.js
omou-frontend/src/components/FeatureViews/Registration/RegistrationLanding.js
omou-frontend/src/components/FeatureViews/Registration/TutoringList.js
omou-frontend/src/components/FeatureViews/Registration/registration.scss

Filters do not override previous filters in the Registration Landing

---

omou-frontend/src/actions/rootActions.js
omou-frontend/src/components/FeatureViews/Registration/RegistrationLanding.js

Fix spacing issues and filters not showing on mobile

---

omou-frontend/src/components/Navigation/Navigation.js

Fix accounts highlighting

---

src/components/FeatureViews/Search/Search.js
src/components/FeatureViews/Search/Search.scss

Fixed buttons so that they would touch the bar.
Added some css styling on primary-filter dropdown.

Search bar style

---

src/components/BackButton.js
src/components/FeatureViews/Accounts/Accounts.js
src/components/FeatureViews/Accounts/Accounts.scss
src/components/FeatureViews/Accounts/ProfileCard.js
src/components/FeatureViews/Accounts/ProfileHeading.js
src/components/FeatureViews/Accounts/TabComponents/CourseViewer.js
src/components/FeatureViews/Accounts/TabComponents/Notes.js
src/components/FeatureViews/Accounts/TabComponents/ParentContact.js
src/components/FeatureViews/Accounts/UserProfile.js
src/components/Navigation/Navigation.js
src/components/Navigation/Navigation.scss
src/theme/sizes.scss

@NeilAllavarpu 
fixed spacing and sorts alphabetically. looks a lot better on responsive views.

Accounts updated

---

src/actions/rootActions.js
src/components/Form/Form.js

parent changing on student editing, parent info grayed out when one is selected, blah, doesnt say registeration if it is an edit (3 things).

fixed 2 things

---

src/components/FeatureViews/Accounts/TabComponents/CourseSessionStatus.js
src/components/FeatureViews/Registration/RegistrationReceipt.js
src/components/Form/PriceQuoteForm.js

payment select needed to pay,  fixed a couple bugs

---

src/components/FeatureViews/Registration/CourseList.js
src/components/FeatureViews/Registration/RegistrationReceipt.js

Added a simple regex to correct the date.
The issue was that new Date was taking the utc date.
This post explains it better:
https://stackoverflow.com/questions/7556591/is-the-javascript-date-object-always-one-day-off

Fixed reciept dates

---

src/components/FeatureViews/Accounts/TabComponents/CourseSessionStatus.js
src/components/FeatureViews/Accounts/TabComponents/TabComponents.scss
src/components/Form/PriceQuoteForm.js

This adresses #213 & #234 changes are on PriceQuoteForm

Link-Enrollements

---

src/components/FeatureViews/Accounts/ProfileCard.js
src/components/FeatureViews/Accounts/ProfileHeading.js
src/components/FeatureViews/Accounts/UserProfile.js

userID-topLeft-#171

---

src/components/FeatureViews/Accounts/TabComponents/InstructorCourses.js
src/components/FeatureViews/Accounts/TabComponents/StudentCourseViewer.js
src/components/FeatureViews/Accounts/TabComponents/TabComponents.scss
src/components/FeatureViews/Scheduler/EditSessionView.js

Fixed-Column-Spacing

---

src/components/Form/Form.js

Fix form title

---

src/actions/multiCallHooks.js
src/components/FeatureViews/Accounts/TabComponents/PaymentTable.js

does not make any more duplicate enrollments

---

src/components/Form/Form.js
src/components/Form/FormUtils.js

Async Instructor Select

---

src/actions/apiActions.js
src/components/FeatureViews/Registration/CourseList.js
src/components/Form/Form.js
src/components/Form/FormUtils.js
src/reducers/searchResultsReducer.js
src/reducers/usersReducer.js

- updated search account endpoint to reflect mat's new search endpoint response
- updated weeklySessionParser() function to include the first week

made some random fixes

---

src/index.js

Change basename, register service worker

---

src/actions/apiActions.js
src/components/FeatureViews/Registration/RegistrationCart.js
src/utils.js

The course Dates were being created incorrectly. This branch fixes that bug

Fixed-DateTime

---

src/components/FeatureViews/Registration/RegistrationLanding.js

Fix registration loading bug

---

src/components/FeatureViews/Registration/RegistrationLanding.js
src/components/Form/Form.js
src/components/InstructorConflictCheck.js
src/utils.js

Instructor conflict

---

src/components/FeatureViews/Accounts/TabComponents/ParentContact.js
src/components/FeatureViews/Accounts/TabComponents/PaymentHistory.js
src/components/FeatureViews/Accounts/TabComponents/StudentCourseViewer.js
src/components/FeatureViews/Accounts/UserProfile.js
src/components/FeatureViews/AdminPortal/UnpaidSessions.js
src/components/FeatureViews/Notes/Notes.js
src/components/FeatureViews/Registration/registration.scss
src/theme/muiTheme.js
src/utils.js

Added badge to notes tab to indicated the number of important notes, and added unpaid sessions fix with a nice card to show no unpaid sessions

Note Badge + Unpaid Session Fix

---

src/actions/adminActions.js
src/components/FeatureViews/Accounts/TabComponents/EnrollmentView.js
src/components/FeatureViews/Accounts/TabComponents/PaymentTable.js
src/components/FeatureViews/Accounts/TabComponents/StudentCourseViewer.js
src/components/FeatureViews/AdminPortal/AdminActionCenter.js
src/components/FeatureViews/AdminPortal/AdminPortal.js
src/components/FeatureViews/AdminPortal/AdminPortal.scss
src/components/FeatureViews/AdminPortal/AdminPortalHome.js
src/components/FeatureViews/AdminPortal/AdminUtils.js
src/components/FeatureViews/AdminPortal/DiscountList.js
src/components/FeatureViews/AdminPortal/DiscountRow.js
src/components/FeatureViews/AdminPortal/ManageCategories.js
src/components/FeatureViews/AdminPortal/ManageDiscounts.js
src/components/FeatureViews/AdminPortal/TuitionRules.js
src/components/FeatureViews/AdminPortal/UnpaidSessionCard.js
src/components/FeatureViews/AdminPortal/UnpaidSessions.js
src/components/FeatureViews/Registration/RegistrationCourseEnrollments.js
src/components/NoListAlert.js
src/reducers/adminReducer.js

Not 100% done (still need to work on TuitionRules), but did most of it.

Rewrite Admin code

---

src/actions/adminActions.js
src/components/FeatureViews/AdminPortal/AdminPortal.scss
src/components/FeatureViews/AdminPortal/TuitionRules.js

Rewrite TuitionRules.js

---

src/components/FeatureViews/Scheduler/DisplaySessionView.js
src/components/FeatureViews/Scheduler/NotEnrolledStudentDialog.js
src/components/FeatureViews/Scheduler/scheduler.scss
src/components/Routes/RootRoutes.js
src/utils.js

Displaying a dialog that will show when we are in the "DisplayMoreSessions" component. Clicking the back button or outside of the box will take you  back to scheduler. #330

Rerouted sessions url

---

src/components/FeatureViews/Search/NoResults/NoResultsPage.js

Fixed Typography in "No results page"

---

src/components/FeatureViews/Notes/Notes.js

Note Text Field Spacing 

---

src/components/FeatureViews/Accounts/UserProfile.js
src/components/FeatureViews/Notes/Notes.js
src/components/FeatureViews/Registration/RegistrationCourse.js

Gave the tooltip title of "This is an Important Note". #363

Added Tooltip to 'UserProfile.js' and 'RegistrationCourse.js'

---

src/components/BackButton.js
src/components/FeatureViews/Search/SearchResults.js

1. made the backbutton a functional component, you can use the back button anyway and give it a prop of btnText="{the text you want}"
2. added the back button to search results 
Ref: #368

updated search results & backbutton

---

package.json
src/actions/multiCallHooks.js
src/components/FeatureViews/Accounts/TabComponents/InstructorCourses.js
src/components/FeatureViews/Accounts/TabComponents/PaymentHistory.js
src/components/FeatureViews/Accounts/TabComponents/PaymentTable.js
src/components/FeatureViews/Accounts/TabComponents/StudentCourseViewer.js
src/components/FeatureViews/Registration/CourseList.js
src/components/FeatureViews/Registration/PaymentReceipt.js
src/components/FeatureViews/Registration/RegistrationCourse.js
src/components/FeatureViews/Registration/RegistrationCourseEnrollments.js
src/components/FeatureViews/Registration/RegistrationLanding.js
src/components/FeatureViews/Registration/TutoringList.js
src/components/Form/Form.js
src/components/Form/RegistrationReceipt.js
src/components/Routes/RootRoutes.js
src/queryFragments.js
src/reducers/courseReducer.js
src/utils.js

Migrated - Registration Landing and Registration Course

Course Model GraphQL Migration

---

package-lock.json
package.json
src/components/FeatureViews/Accounts/Accounts.js
src/components/FeatureViews/Accounts/ComponentViewer.js
src/components/FeatureViews/Accounts/ProfileCard.js
src/components/FeatureViews/Notes/Notes.js
src/queryFragments.js

Notes and some of accounts i guess

Accounts graphql

---

src/components/FeatureViews/Scheduler/scheduler.scss

Addresses #353, changed color to #EBFAFF

Scheduler-current-day-background

---

src/components/FeatureViews/AdminPortal/AdminActionCenter.js
src/components/Form/Fields.js
src/components/Form/FormFormats.js
src/components/Form/FormReceipt.js

fixed bugs with the form + receipt

Course form

---

src/components/FeatureViews/Accounts/Accounts.js
src/theme/secondaryTheme.js

Changed background to transparent & changed textColor to omouBlue

Changed MUI table theme

---

src/components/Navigation/AuthenticatedNav.js
src/components/Navigation/Navigation.scss

Bug Hunting Event bug# A078 "only Nelson can view" message page when clicking at white border of profile icon
Some nice quality of life changes: 
* The button is shown if your name is 'NeLSoN' (making it harder to get to this treasure).
* I've made the pointer ```display: default``` whenever you hover over the CATS button. 
* Added margin right to give space for the avatar and logout button
* Added negative margin to offset if someone is ever 'NeLSoN' and the link appears.

Fixing cats page

---

src/components/FeatureViews/Accounts/Accounts.js
src/components/FeatureViews/Accounts/Accounts.scss
src/components/FeatureViews/Registration/CourseList.js
src/components/FeatureViews/Registration/RegistrationActions.js
src/components/FeatureViews/Registration/registration.scss
src/components/FeatureViews/Scheduler/scheduler.scss
src/components/OmouComponents/BackButton.js

Account List and Grid view are smaller #455 
Registration - Fixed spacing between setting a parent and shopping cart icon #482 
Fixed format to match exactly as the figma shows. #484 
edit: wrong link

Account bug fixes

---

src/components/FeatureViews/Scheduler/scheduler.scss
src/components/OmouComponents/BackButton.js

Changed icon to ArrowBackIos in the <BackButton/> #445 
Gave the Scheduler a width of 100%. #444

A011 Back button & A010 Resource view width

---

src/components/Authentication/NewAccount.js
src/components/FeatureViews/Registration/PaymentReceipt.js
src/components/FeatureViews/Registration/RegistrationCourseEnrollments.js
src/components/FeatureViews/Scheduler/Scheduler.js
src/components/Form/Fields.js

#519 Added a period 
#460 create parent password validations changed to: 
Must Contain 8 Characters, One Uppercase, One Lowercase, One Number and One Special Case Character
#472 No back button in scheduler 
#516 Added space in unenroll popup window

Calvin squashes bugs

---

src/components/FeatureViews/Accounts/TabComponents/EnrollmentView.js

The moment component was missing a "m". I've added it.
```   
<Moment
date={startTime}
format="h:m(+m) A"/> 
{" - "}
<Moment
date={endTime}
format="h:mm A"/>
```
https://github.com/omou-org/front-end/issues/518

#518 Missing 0 in details page

---

src/components/FeatureViews/Scheduler/DisplaySessionView.js

fixed bug where tutoring options would display on class page

Tutoring options fix

---

src/components/Form/Fields.js
src/components/Form/FormFormats.js

Added noOptionsText prop to Fields.DataSelect components within parentSelect, categorySelect, and schoolSelect functions in FormFormats.js. Also put {...props} on its own line in Fields.js line 79.

Fix for Issue A027 (Autocomplete No Options Text) and A045 (Phone Number regex)

---

src/theme/muiTheme.js

updated mui theme typography to have dahl specifics

Mui Theme Typography

---

src/theme/muiTheme.js

Added body paragraph and link stylings

Typography Mui theme

---

src/components/Routes/RootRoutes.js
src/theme/ThemedComponents/Badge/BadgeDemo.js
src/theme/ThemedComponents/Badge/LabelBadge.js

Created a route to show the demo for LabelBadge.js

Created demo route for Badges

---

src/components/Routes/RootRoutes.js
src/theme/ThemedComponents/Typography/TypographyDemo.js
src/theme/muiTheme.js

Added the demo to the ThemedComponents folder for testing/viewing.

Added Typography demo to ThemedComponents

---

src/components/Routes/RootRoutes.js
src/theme/ThemedComponents/Typography/TypographyDemo.js
src/theme/muiTheme.js

Updated variants to use google fonts per design team

Updated variants

---

src/components/Routes/DemoRoutes.js
src/components/Routes/RootRoutes.js
src/theme/muiTheme.js

Consolidated all demo routes into single DemoRoutes.js component.

Organize routes

---

src/components/FeatureViews/Registration/RegistrationLanding.js

Added a dropdown menu allowing for sort by course title and remaining seats.

Added sort feature to Registration Landing

---

src/components/Routes/RootRoutes.js
src/theme/ThemedComponents/Badge/BadgeDemo.js
src/theme/ThemedComponents/Badge/LabelBadge.js

Changed the type prop to variant in the LabelBadge component

Type to variant badges

---

src/components/FeatureViews/Accounts/ComponentViewer.js
src/components/FeatureViews/Accounts/ProfileHeading.js
src/components/FeatureViews/Accounts/UserAccessControl.js
src/components/FeatureViews/Accounts/UserProfile.js
src/components/Navigation/Navigation.js

updated UserAccessControl

---

src/components/FeatureViews/Accounts/Accounts.js
src/components/FeatureViews/Accounts/TabComponents/EnrollmentView.js
src/components/FeatureViews/Accounts/UserProfile.js
src/components/FeatureViews/AdminPortal/AdminPortal.js
src/components/FeatureViews/Courses/CourseManagementContainer.js
src/components/FeatureViews/Registration/RegistrationLanding.js
src/components/FeatureViews/Scheduler/Scheduler.js
src/components/Form/OldForm.js
src/components/Navigation/Navigation.scss
src/components/OmouComponents/Loading.js
src/components/Routes/RootRoutes.js

Updated background on all views to match Dahl design.

Background style

---

src/theme/muiTheme.js
src/theme/theme.scss

Updated font sizes of H4, Body, Body Bold, Body Paragraph, and Links corresponding with information given from the design team on figma

Text Update

---

src/theme/ThemedComponents/Badge/LabelBadge.js

Implemented Gaby's changes to Label Badges. They now have a set padding and not a minWidth

Label badges now have a fixed padding instead of a fixed min width

---

src/components/FeatureViews/Accounts/ComponentViewer.js
src/components/FeatureViews/Accounts/ProfileHeading.js
src/components/FeatureViews/Accounts/TabComponents/ParentContact.js
src/components/FeatureViews/Accounts/UserAccessControl.js
src/components/FeatureViews/Accounts/UserProfile.js

Updated Profile heading
TODO:
Tests - Need write tests for logging into different accounts and checking profiles with search.

Profile heading

---

src/components/FeatureViews/Accounts/UserProfile.js

Added a GraphQL call to have access to account notes in UserProfile. From the notes, the tab will display number of notes marked as important, if any.

Notes tab in UserProfile.js now updates # of impt. notes

---

src/components/FeatureViews/Courses/CourseManagementContainer.js
src/components/FeatureViews/Courses/StudentBadge.js

I am finishing my last pass at reviewing this code.

Course management student tags

---

src/components/FeatureViews/Accounts/Accounts.js

Changed the list view and grid view buttons in Accounts to a button group that utilizes only icons

Accounts view button toggle

---

src/components/FeatureViews/Accounts/ProfileCard.js
src/theme/muiTheme.js

updated accounts card style per Design team's instruction regarding card actions

dahl accounts card update

---

src/components/OmouComponents/CourseAvailabilities.js

Created CourseAvailability component to display courses with multiple sessions per week.

Added CourseAvailabilites component

---

src/utils.js

This is a function that is used in CourseAvailabilities component that we merged in yesterday that I forgot to add into that PR.

Added sessionsAtSameTimeInMultiDayCourse function to utils

---

src/components/FeatureViews/Courses/CourseManagementContainer.js

Corrected the date comparison in course management.

Date comparison course management

---

src/components/FeatureViews/Accounts/TabComponents/EnrollmentView.js
src/components/FeatureViews/AdminPortal/DiscountRow.js
src/components/FeatureViews/Availability/DayAvailabilityEntry.js
src/components/FeatureViews/Availability/TimeAvailabilityContainer.js
src/components/FeatureViews/Notes/Notes.js
src/components/FeatureViews/Registration/CourseList.js
src/components/FeatureViews/Registration/RegistrationCart/RegistrationCartContainer.js
src/components/FeatureViews/Registration/RegistrationCourseEnrollments.js
src/components/FeatureViews/Registration/SelectParentDialog.js
src/components/FeatureViews/Scheduler/DisplaySessionView.js
src/components/FeatureViews/Scheduler/NotEnrolledStudentDialog.js
src/components/FeatureViews/Scheduler/SessionView.js
src/components/Form/Form.js
src/components/Form/OldForm.js
src/components/OmouComponents/AddSessions.js
src/components/OmouComponents/InstructorConflictCheck.js
src/theme/muiTheme.js

Updated the muiTheme as well as the individual tags with disableTypography. With research, it looks like this the most recommended way, since dialogTitle (FOR SOME REASON) automatically creates an h2 tag with h6 variant stylings, so overrides and global do not work.

Updated dialog title to take h4 stylings

---

src/actions/authActions.js
src/components/Navigation/AuthenticatedNavigationView.js
src/components/OmouComponents/IdleTimerPrompt.js

reset token after user activity. I'm a derp and forgot this in my earlier PR

idle timer token reset

---

src/components/FeatureViews/Accounts/UserProfile.js
src/components/FeatureViews/Notes/Notes.js

renamed notes to accountNotes

---

src/components/FeatureViews/Accounts/Accounts.js
src/components/FeatureViews/Accounts/ProfileCard.js
src/components/FeatureViews/Accounts/ProfileHeading.js
src/components/FeatureViews/Accounts/TabComponents/ParentContact.js
src/components/FeatureViews/Accounts/TabComponents/StudentInfo.js
src/components/FeatureViews/AdminPortal/AdminActionCenter.js
src/components/Form/FormPage.js
src/components/OmouComponents/AddItemButton.js
src/components/Routes/RootRoutes.js
src/theme/muiTheme.js

1. Added an action for the form routes to be able to change the action on the form. New route = /form/:action/:type/id?
2. Fixed margin and spacing with each profile card. Box shadow and margin
#715

Updates for 715

---

src/components/FeatureViews/Invoices/InvoiceReceipt.js

- parse payment method correctly
- remove typo

invoice receipt fixes

---

src/components/FeatureViews/Invoices/InvoiceReceipt.js
src/components/FeatureViews/Invoices/InvoiceTable.js
src/components/FeatureViews/Invoices/Invoices.js

Invoices styling fix from feedback from designers:
- date range highlight color is omouBlue
- button in date range has no border
- Invoice Table pagination renders conditionally on # of invoices

Invoices style fixes

---

src/components/FeatureViews/Courses/ClassEnrollmentList.js
src/components/FeatureViews/Enrollment/EnrollmentActions.js
src/components/FeatureViews/Enrollment/EnrollmentDetails.js
src/components/FeatureViews/Enrollment/EnrollmentSessionRow.js
src/components/FeatureViews/Enrollment/EnrollmentSummaryTab.js
src/components/FeatureViews/Enrollment/EnrollmentView.js
src/components/FeatureViews/Enrollment/UnenrollButton.js
src/components/FeatureViews/Registration/RegistrationCourse.js
src/components/OmouComponents/AddSessions.js
src/utils.js

- Bring top half of Enrollment View into line with Figma design
Current Screenshot
Figma Screenshot

Enrollmentview details
